#pragma once
#define MATRIX_ROWS 3
#define MATRIX_COLS 4
#define DIODE_DIRECTION ROW2COL
#define MATRIX_ROW_PINS { GP9, GP11, GP12 }
#define MATRIX_COL_PINS { GP0, GP2, GP4, GP6 }

#define WS2812_DI_PIN GP29
#define WS2812_BYTE_ORDER WS2812_BYTE_ORDER_RBG
#define RGBLIGHT_LED_COUNT 1
#define RGBLIGHT_EFFECT_BREATHING
#define RGBLIGHT_EFFECT_RAINBOW_MOOD
//#define RGB_DISABLE_WHEN_USB_SUSPENDED !Funktioniert seit neustem nicht!
//#define RGB_MATRIX_SLEEP !macht einfach nichts! 
#define RGBLIGHT_SLEEP

#define MIDI_ADVANCED

#define ENCODER_A_PINS { GP15 }
#define ENCODER_B_PINS { GP27 }
#define ENCODER_DIRECTION_FLIP

#define DYNAMIC_KEYMAP_MACRO_COUNT 64